openapi: 3.0.0
info:
  title: JobSwipe API
  description: API для взаимодействия соискателей и работодателей. Поддерживает регистрацию, аутентификацию, профили, вакансии и чаты.
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: Local server

tags:
  - name: Auth
    description: Регистрация и вход
  - name: Profiles
    description: Профили пользователей
  - name: Employer
    description: Функции для работодателя
  - name: JobSeeker
    description: Функции для соискателя
  - name: Chats
    description: Сообщения и чаты
  - name: Upload
    description: Загрузка файлов

paths:
  /auth/register:
    post:
      tags: [Auth]
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [login, password, role]
              properties:
                login:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [job_seeker, employer]
      responses:
        '201':
          description: Успешная регистрация
        '500':
          description: Ошибка регистрации

  /auth/login:
    post:
      tags: [Auth]
      summary: Вход пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [login, password]
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Неверные данные

  /profiles/jobSeeker:
    get:
      tags: [Profiles]
      summary: Получить профиль соискателя
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Профиль найден
        '403':
          description: Нет доступа

    post:
      tags: [Profiles]
      summary: Создать/обновить профиль соискателя
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                last_name:
                  type: string
                first_name:
                  type: string
                gender:
                  type: string
                age:
                  type: integer
                city:
                  type: string
                education:
                  type: string
                about:
                  type: string
                profession:
                  type: string
                job_position:
                  type: string
                skills:
                  type: string
                resume:
                  type: string
      responses:
        '200':
          description: Профиль обновлён
        '201':
          description: Профиль создан

  /jobseeker/vacancies:
    get:
      tags: [JobSeeker]
      summary: Получить список вакансий
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Успешно

  /jobseeker/like:
    post:
      tags: [JobSeeker]
      summary: Лайк вакансии
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [vacancy_id]
              properties:
                vacancy_id:
                  type: integer
      responses:
        '201':
          description: Лайк добавлен

  /employer/vacancies:
    get:
      tags: [Employer]
      summary: Получить вакансии работодателя
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список вакансий

    post:
      tags: [Employer]
      summary: Создать вакансию
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [title, description, location]
              properties:
                title:
                  type: string
                description:
                  type: string
                requirements:
                  type: string
                location:
                  type: string
      responses:
        '201':
          description: Вакансия создана

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
